[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "word-learner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "PyQt6>=6.7.0"
]
